blank_issues_enabled: false
contact_links:
  - name: Questions & Ideas / Вопросы и идеи
    url: https://github.com/$\{OWNER\}/$\{REPO\}/discussions
    about: Use Discussions for questions and open-ended ideas
